# Thank you for downloading SimpleAnnouncer! If you like my plugin, please leave a review.
# Spigot: https://www.spigotmc.org/resources/simpleannouncer.106836/
#
# All types of standard colour codes are supported, including Hexadecimal, e.g. &#FFFFFF, or &c
# Non-Hex colour codes: http://ess.khhq.net/mc/
#
# PlaceholderAPI placeholders are supported if your server has PlaceholderAPI installed.
# e.g. - "&cHello there, %player_name%. If you need help, use /helpop"
#
# Hover-able text is also supported! Simply surround what you wish to make appear in {}. Use \n for new lines.
# e.g. - "&cHello there, %player_name%. {&7This is a multi-line\n&7message!}"

# This is how long the plugin will wait before sending another announcement in minutes.
timer: 1

# These are selected at random and queued.
messages:
  - "&cTest 1"
  - "&aTest 2"
  - "&6Test 3"
  - "&4Test 4"